//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top10.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_
    {
        public int Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<bool> IsMale { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
